spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: root
    password: 20231028

  mvc:
    hidden-method:
      filter:
        enabled: true
file:
  resources:
    path: src/main/resources/

  domains:
    customer:
      file-name: blacklist.csv

    voucher:
      file-name: voucher.json
