spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prod
    username: root
    password: 20231028
  mvc:
    hidden-method:
      filter:
        enabled: true
---
spring:
  config:
    activate:
      on-profile: file
file:
  resources:
    path: src/main/resources/

  domains:
    customer:
      file-name: blacklist.csv

    voucher:
      file-name: voucher.json
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 20231028

